//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCalendar.PSCalendarServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PSCalendarServiceRef.ICalendar")]
    public interface ICalendar {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendar/GetDate", ReplyAction="http://tempuri.org/ICalendar/GetDateResponse")]
        void GetDate();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalendarChannel : PSCalendar.PSCalendarServiceRef.ICalendar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalendarClient : System.ServiceModel.ClientBase<PSCalendar.PSCalendarServiceRef.ICalendar>, PSCalendar.PSCalendarServiceRef.ICalendar {
        
        public CalendarClient() {
        }
        
        public CalendarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalendarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalendarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalendarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetDate() {
            base.Channel.GetDate();
        }
    }
}
