//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCalendarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.SyncAccountLog = new HashSet<SyncAccountLog>();
            this.SyncAccountEvent = new HashSet<SyncAccountEvent>();
        }
    
        public System.Guid EventGuid { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> NiceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SyncAccountLog> SyncAccountLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SyncAccountEvent> SyncAccountEvent { get; set; }
    }
}
