//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCalendarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleCalendarSyncView
    {
        public int EventId { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public System.Guid EventGuid { get; set; }
        public Nullable<int> SyncAccountId { get; set; }
        public string GoogleCalendarId { get; set; }
        public string Email { get; set; }
    }
}
