//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCalendarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleCalendarSyncView
    {
        public Nullable<int> NiceId { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Type { get; set; }
        public System.Guid EventGuid { get; set; }
        public string GoogleCalendarEventId { get; set; }
        public bool EventDeleted { get; set; }
        public Nullable<bool> SyncAccountTobeDeleted { get; set; }
        public Nullable<bool> SyncAccountDeleted { get; set; }
        public string GoogleCalendarId { get; set; }
        public string Email { get; set; }
    }
}
