//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCalendarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncAccountEvent
    {
        public int SyncAccountId { get; set; }
        public System.Guid EventGuid { get; set; }
        public string GoogleCalendarId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual SyncAccount SyncAccount { get; set; }
    }
}
